### ISSUE TITLE
Hangs on large files (and user interaction in general, probably)

### ISSUE THREAD

**Issue by pkgw** [Lindydancer/e2ansi#3]
I'm using e2ansi as a filter for less. When I try to page a very large file, nothing seems to happen. But if I hit ^C, I get output that looks like this:

```
File goreham.log is large (10.6M), really open? (y or n)
```

So I believe that e2ansi is hanging because emacs is prompting for user input. I'm launching emacs with a `--batch` option, so I'd have thought that prompts for user input would be turned off, but apparently not. I'd argue that, if possible, Emacs variables should be twiddled so that prompts of this kind are disabled, and that the answer to this particular question ("open large file?") should be "yes".

**Comment by Lindydancer** [comment]
Hi!

Thanks for spotting this. I just released a new version where it's been
fixed. All that was needed was to set `large-file-warning-threshold` to nil
when opening a file in batch mode.

    -- Anders
