### ISSUE TITLE
Error: "Symbol's value as variable is void: special-mode-map"

### ISSUE THREAD

**Issue by israelmcmc** [Lindydancer/e2ansi#8]
Hi

I've successfully been able to use `e2ansi` with `less` using a manual pipe but not with the input preprocessor indicated by LESSOPEN. This works:

```
emacs --batch -l ~/.emacs -l bin/e2ansi-cat foo | less -R
```

but this

```
export LESSOPEN="|emacs --batch -l ~/.emacs -l bin/e2ansi-cat %s"
less -R foo
```

gives the error:

> Symbol's value as variable is void: special-mode-map

Any idea what can be happening? 

I'm using `emacs` version 24.5.1, `less` version 530 and the contents of `~/.emacs` is 

```
(add-to-list 'load-path "~/.emacs.d/e2ansi/")
(add-to-list 'load-path "~/.emacs.d/face-explorer/")
```

Thank you!

**Comment by Lindydancer** [comment]
My initial guess is that 'less' launch an older Emacs version. The keymap
special-mode-map was surely defined in 24.5 (I haven't access to a computer
right now to verify this).

This can be a problem with your path setup or if you have defined 'emacs'
as an alias (which 'less doesn't see).

    -- Anders


Den mån 9 juli 2018 22:28israelmcmc <notifications@github.com> skrev:

**Comment by israelmcmc** [comment]
Yes, it was an alias I had forgotten I had set, now it works.

Thanks a lot, that was quick!

**Comment by Lindydancer** [comment]
Glad I could help!

    -- Anders


Den mån 9 juli 2018 23:16israelmcmc <notifications@github.com> skrev:
